server:
  port: 8086

spring:
  application:
    name: notification
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: 1111
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  config:
    import: secret.yml

  kafka:
    bootstrap-servers: localhost:9092
    partitions: 3
    topics:
      email: email-notification
      phone: phone-notification
      router: user-list-router




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true