server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/users/**
        - id: group
          uri: lb://GROUP
          predicates:
            - Path=/api/v1/groups/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/v1/notifications/**
        - id: template
          uri: lb://TEMPLATE
          predicates:
            - Path=/api/v1/templates/**