server:
  port: 8088

spring:
  application:
    name: file-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 1111
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true