server:
  port: 8081

spring:
  application:
    name: group
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/group
    username: postgres
    password: 1111
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: group-service-consumer
      properties:
        spring.json.trusted.packages: "com.george.core"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
