server:
  port: 1000

spring:
  datasource:
    url: jdbc:postgresql://group-service-postgres:5432/group
  kafka:
    bootstrap-servers: kafka:29092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka