server:
  port: 1003

spring:
  datasource:
    url: jdbc:postgresql://user-service-postgres:5432/user
  kafka:
    bootstrap-servers: kafka:29092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka