server:
  port: 52943

spring:
  application:
    name: rebalancer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: 1111
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    partitions: 3
    topics:
      email: email-notification
      phone: phone-notification
      router: user-list-router

rebalancer:
  seconds-before-resend-pending: 5
  seconds-before-resend-new: 5
  max-amount-to-fetch: 15

springdoc:
  api-docs:
    path: /rebalancer/api-docs



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true